dataset:
  dataset_size: 2500
  max_node_num: 23
  name: barabasi_albert_[15, 17, 19, 21, 23]
dev: !!python/object/apply:torch.device
- cuda
exp_dir: scorematching_gnn/exp
exp_name: barabasi_albert_diff_nodes_small
folder_name: edp-gnn_barabasi_albert_[15, 17, 19, 21, 23]__Aug-07-15-50-45_2986529
mcmc:
  eps:
  - 1.0
  - 0.5
  - 0.1
  fixed_node_number: true
  grad_step_size:
  - 0.05
  - 0.005
  - 0.0005
  name: langevin
  step_num: 300
model:
  models:
    model_1:
      channel_num_list:
      - 2
      - 4
      - 4
      - 4
      - 2
      dropout_p: 0.0
      feature_nums:
      - 16
      - 16
      - 16
      - 16
      - 16
      gnn_hidden_num_list:
      - 16
      - 16
      - 16
      - 16
      name: gin
      use_norm_layers: false
  name: edp-gnn
  stack_num: 1
model_save_dir: scorematching_gnn/exp/barabasi_albert_diff_nodes_small/edp-gnn_barabasi_albert_[15,
  17, 19, 21, 23]__Aug-07-15-50-45_2986529/models
run_id: '2986529'
sample:
  batch_size: 32
  num_samples: 100
save_dir: scorematching_gnn/exp/barabasi_albert_diff_nodes_small/edp-gnn_barabasi_albert_[15,
  17, 19, 21, 23]__Aug-07-15-50-45_2986529
seed: 7892
test:
  batch_size: 32
  split: 0.2
train:
  batch_size: 32
  lr_dacey: 0.999
  lr_init: 0.001
  max_epoch: 5001
  momentum: 0.9
  sample_interval: 2500
  save_interval: 2500
  shuffle: true
  sigmas:
  - 0.03
  - 0.08222222
  - 0.13444444
  - 0.18666667
  - 0.23888889
  - 0.29111111
  - 0.34333333
  - 0.39555556
  - 0.44777778
  - 0.5
  weight_decay: 0.0
