device: cuda:1

graph_generation:
  method: load_graph_dataset
  params:
    filename: data/test_deezer_ego.pkl
    n_sim: 100

score_model:
  model_file: deezer_egonets
  max_nodes: 25
  sigmas:
    max: 0.5
    min: 0.03
    num: 10
  epsilon: 1.0E-6
  steps: 300
  temperature: 1.0
  num_samples: 10

ggm_simulation:
  obs_ratio_list: [0.15, 0.35, 0.85, 2.0]
  prior_Theta: wishart_prior
  psd_trials: 10
  nans: 0.5
  # one_zero_ratio:
  n_proportional: True

lambda_glasso:
  fun: lambda_generic
  params:
    a: 2.10615704
    b: -5.49361124
    c: 18.04472622
  # # Use the ones below when estimating the whole graph (i.e., nans = 1.0)
  # params:
  #   a: 3.16160777
  #   b: -17.52335464
  #   c: 45.6692579