device: cuda:1
parallel: True
n_jobs: 15

graph_generation:
  method: generate_grids
  params:
    m_min: 5
	  m_max: 9
	  min_nodes: 40
	  max_nodes: 49
	  min_random_edges: 2
	  max_random_edges: 5
    n_sim: 100
  
score_model:
  model_file: grids
  max_nodes: 49
  sigmas:
    max: 0.5
    min: 0.03
    num: 10
  epsilon: 1.0E-6
  steps: 300
  temperature: 1.0
  num_samples: 10

ggm_simulation:
  obs_ratio_list: [0.15, 0.35, 0.85, 2.0]
  prior_Theta: wishart_prior
  psd_trials: 10
  nans: 0.2
  # one_zero_ratio:
  n_proportional: True

lambda_glasso:
  fun: lambda_generic
  params:
    a: 4.61577605
    b: -28.03207726
    c: 78.38257537